apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sunsetapis.sunsetapi.com
  labels:
    name: sunsetapi-operator
spec:
  group: sunsetapi.com
  versions:
    - name: v1
      served: true
      storage: true
      # Support status subresource required by ansible-operator
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                  sunsetAPICount:
                    type: string
  scope: Namespaced
  names:
    plural: sunsetapis
    singular: sunsetapi
    kind: SunsetApi
    shortNames:
    - sa
