apiVersion: v1
kind: ServiceAccount
metadata:
  name: sunsetapi-operator-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sunsetapi-reader
rules:
- apiGroups: ["sunsetapi.com"]
  resources: ["sunsetapis"]
  verbs: ["get", "list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sunsetapi-operator-binding
subjects:
- kind: ServiceAccount
  name: sunsetapi-operator-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
